//! Subagent prompt enhancement — injects tool guidance, environment context,
//! and safety constraints into the subagent's system prompt.
//!
//! ## Why this exists
//!
//! Claude Code's SubAgent (AgentTool/forkSubagent) builds a **complete but
//! compact** system prompt for each sub-agent that includes:
//!
//! 1. The agent's own identity/task description (from the definition)
//! 2. A tool inventory listing available tools and their descriptions
//! 3. Tool usage strategy (parallel execution, error handling, etc.)
//! 4. Environment context (OS, shell, CWD, project type)
//! 5. Safety constraints (no destructive operations, etc.)
//!
//! Without this, the subagent only receives the raw `definition.system_prompt`
//! and relies entirely on the API-level `tools` parameter for tool awareness.
//! While modern LLMs can use tools from API definitions alone, they perform
//! significantly better with explicit usage strategies in the system prompt.
//!
//! ## What this does NOT include
//!
//! - DAEDALUS.md / project rules (subagent context is isolated)
//! - Memory context (subagent has no conversation history)
//! - Main agent's soul/personality (subagent has its own identity)
//! - Full prompt builder sections (kept compact to save tokens)

use crate::tools::ToolInfo;

/// Build the effective system prompt for a subagent.
///
/// Appends tool guidance, environment context, and safety constraints
/// to the subagent's base system prompt. If no tools are available,
/// only environment context is appended.
///
/// This mirrors Claude Code's `forkSubagent` behavior: the sub-agent
/// gets a self-contained prompt with everything it needs to operate
/// effectively, without inheriting the parent agent's full prompt.
#[allow(dead_code)]
pub fn build_effective_prompt(
    base_prompt: &str,
    tool_infos: &[ToolInfo],
    has_tools: bool,
) -> String {
    build_effective_prompt_with_context(base_prompt, tool_infos, has_tools, None)
}

/// Build the effective system prompt with optional shared context.
///
/// When `shared_context` is provided, it is injected as a read-only
/// `<shared_context>` section between the base prompt and tool guidance.
/// This breaks the information silo between parallel subagents by giving
/// each one a common understanding of the project's architecture, shared
/// types, and cross-module dependencies.
///
/// The shared context is typically generated by the orchestrator (or plan
/// agent) and includes:
/// - Project architecture overview
/// - Key shared types and traits
/// - Cross-module dependency map
/// - Common patterns and conventions
pub fn build_effective_prompt_with_context(
    base_prompt: &str,
    tool_infos: &[ToolInfo],
    has_tools: bool,
    shared_context: Option<&str>,
) -> String {
    let mut parts: Vec<String> = Vec::with_capacity(5);

    // ── Prompt ordering: cache-friendly layout ──
    //
    // LLM providers (Anthropic, OpenAI) cache by **prefix match** — the
    // longer the shared prefix across requests, the higher the cache hit
    // rate. For parallel subagents that share the same tools but differ
    // in identity/task, we place stable/shared content FIRST and
    // per-agent-varying content LAST:
    //
    //   1. environment   — identical across ALL subagents (OS, CWD, date)
    //   2. constraints    — identical across all subagents with same tool set
    //   3. tool_guidance  — identical when tool whitelist matches
    //   4. shared_context — identical within the same orchestrator batch
    //   5. base_prompt    — per-agent identity (varies) → placed LAST
    //
    // This maximizes the shared prefix length, enabling 60-80% cache hit
    // rates across a batch of 3-5 parallel subagents (vs. ~5% with the
    // old layout where base_prompt was first).

    // 1. Environment context (identical across ALL subagents)
    parts.push(build_environment_section());

    // 2. Safety constraints (identical for same tool availability)
    parts.push(build_constraints_section(has_tools));

    // 3. Tool guidance (identical when tool whitelist matches)
    if has_tools && !tool_infos.is_empty() {
        parts.push(build_tool_guidance_section(tool_infos));
    }

    // 4. Shared context (identical within the same orchestrator batch)
    //    This is the key mechanism for breaking information silos between
    //    parallel subagents. Each subagent receives the same read-only
    //    project overview, enabling cross-module awareness without
    //    sharing mutable state.
    if let Some(ctx) = shared_context {
        if !ctx.trim().is_empty() {
            parts.push(format!(
                "<shared_context>\n\
                 The following project-wide context is shared across all parallel subagents.\n\
                 Use this to understand cross-module interfaces and dependencies.\n\n\
                 {}\n\
                 </shared_context>",
                ctx.trim()
            ));
        }
    }

    // 5. The agent's own system prompt (identity + task description)
    //    Placed LAST so all preceding content forms a shared prefix that
    //    can be cached across parallel subagents.
    parts.push(format!(
        "<agent_identity>\n{}\n</agent_identity>",
        base_prompt
    ));

    parts.join("\n\n")
}

/// Build the environment context section.
///
/// Provides the subagent with basic runtime information so it can
/// make informed decisions about file paths, shell commands, etc.
fn build_environment_section() -> String {
    let os = std::env::consts::OS;
    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/bash".to_string());
    let cwd = std::env::current_dir()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| ".".to_string());

    let today = chrono::Utc::now().format("%Y-%m-%d").to_string();

    format!(
        "<environment>\n\
         Operating system: {os}\n\
         Default shell: {shell}\n\
         Current directory: {cwd}\n\
         Today's date: {today}\n\
         </environment>"
    )
}

/// Build the tool guidance section for subagents.
///
/// This is a **compact** version of the main agent's tool guidance,
/// optimized for token efficiency while preserving the key strategies
/// that improve tool usage quality.
fn build_tool_guidance_section(tool_infos: &[ToolInfo]) -> String {
    // Build tool inventory
    let tool_list: Vec<String> = tool_infos
        .iter()
        .map(|t| {
            format!(
                "- **{}**: {}",
                t.name,
                if t.description.is_empty() {
                    "No description"
                } else {
                    &t.description
                }
            )
        })
        .collect();

    let inventory = tool_list.join("\n");

    // Build a set of available tool names for conditional guidance.
    // This avoids mentioning tools the subagent doesn't have access to,
    // which would waste tokens and confuse the LLM.
    let available: std::collections::HashSet<&str> =
        tool_infos.iter().map(|t| t.name.as_str()).collect();

    // Build "Right tool for the job" guidance — only include tools
    // that are actually in this subagent's filtered tool set.
    let mut tool_hints = Vec::new();
    if available.contains("grep_search") {
        tool_hints.push("   - Exact text/symbol lookup → grep_search");
    }
    if available.contains("read_file") {
        tool_hints.push("   - Known file path → read_file directly");
    }
    if available.contains("search_files") {
        tool_hints.push("   - File name search → search_files");
    }
    if available.contains("list_directory") {
        tool_hints.push("   - Directory listing → list_directory");
    }
    if available.contains("bash") {
        tool_hints.push("   - Shell commands → bash");
    }
    if available.contains("codebase_search") {
        tool_hints.push("   - Semantic code search → codebase_search");
    }
    if available.contains("view_code_item") {
        tool_hints.push("   - View specific symbol definition → view_code_item");
    }

    let tool_hints_section = if tool_hints.is_empty() {
        String::new()
    } else {
        format!(
            "\n\
             3. **Right tool for the job** (use only tools listed above):\n\
             {}\n",
            tool_hints.join("\n")
        )
    };

    // Conditionally include take_note guidance — emphasize immediate recording
    let take_note_hint = if available.contains("take_note") {
        "\n\
         7. **`take_note` discipline** (CRITICAL for long tasks):\n\
            - Call `take_note` IMMEDIATELY when you discover something important — do NOT defer\n\
            - Notes survive context truncation; un-noted findings will be LOST permanently\n\
            - Record findings in the SAME tool_calls batch as the discovery (parallel with next read)\n\
            - Include full evidence (code snippets, line numbers) IN the note — notes are your primary deliverable\n\
            - Anti-pattern: saving all take_note calls for the last 1-2 rounds (this defeats the purpose)\n\
            - Your final text output should be a SHORT summary; detailed findings belong in take_note\n"
    } else {
        ""
    };

    format!(
        "<tools>\n\
         ## Available Tools\n\n\
         {inventory}\n\
         \n\
         ## Tool Usage Strategy\n\
         \n\
         1. **Maximize parallel execution**: When multiple independent operations are needed, \
         execute ALL of them simultaneously.\n\
            - Reading multiple files → parallel\n\
            - Searching different patterns → parallel\n\
            - Only serialize when output of one call is required input for the next\n\
         \n\
         2. **Gather before acting**: Before making changes, first understand the full context. \
         Read relevant files, search for usages, check imports — all in parallel.\n\
         {tool_hints_section}\
         \n\
         4. **Error recovery**: If a tool call fails, analyze why and try a different approach. \
         Do not retry with identical arguments. After 3 failures, switch strategy entirely.\n\
         \n\
         5. **Efficiency**: If you can answer from context already gathered, do so without \
         additional tool calls. Minimize unnecessary operations.\n\
         \n\
         6. **Context budget awareness**: You have a LIMITED context window. Every file you read \
         and every tool result consumes budget. Plan your exploration carefully:\n\
            - Estimate total work before starting (file count × avg size)\n\
            - Reserve ~30% of your rounds for synthesis and verification\n\
            - If you notice responses getting slower, start wrapping up immediately\n\
         {take_note_hint}\
         </tools>"
    )
}

/// Build the safety constraints section.
///
/// Provides guardrails that apply to all subagents regardless of their
/// specific role. These mirror Claude Code's SubAgent constraints.
fn build_constraints_section(has_tools: bool) -> String {
    let mut constraints = Vec::new();

    constraints.push(
        "You are operating in an isolated subagent context with an independent conversation window."
    );
    constraints.push(
        "You do NOT have access to the parent agent's conversation history or memory."
    );
    constraints.push(
        "Your response will be returned to the parent agent as a summary — be thorough but concise."
    );

    if has_tools {
        constraints.push(
            "Present tool results naturally as part of your analysis. \
             Never mention internal tool names or protocols to the user."
        );
        constraints.push(
            "Do not fabricate tool arguments. If you lack required information, \
             search for it using available tools."
        );
    }

    constraints.push(
        "Respond in the same language as the task description. \
         Match the language consistently throughout your entire response \
         (including intermediate thoughts and the final report). \
         Never switch languages mid-response."
    );

    let items: Vec<String> = constraints
        .iter()
        .enumerate()
        .map(|(i, c)| format!("{}. {}", i + 1, c))
        .collect();

    format!(
        "<constraints>\n\
         {}\n\
         </constraints>",
        items.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_effective_prompt_with_tools() {
        let base = "You are a code reviewer.";
        let tools = vec![
            ToolInfo {
                name: "read_file".to_string(),
                description: "Read file contents".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
            ToolInfo {
                name: "grep_search".to_string(),
                description: "Search with regex".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
        ];

        let prompt = build_effective_prompt(base, &tools, true);

        // Cache-friendly ordering: environment first, base_prompt last
        assert!(prompt.starts_with("<environment>"));
        // Base prompt should be wrapped in <agent_identity> and placed last
        assert!(prompt.contains("<agent_identity>"));
        assert!(prompt.contains("You are a code reviewer."));
        // Should contain environment section
        assert!(prompt.contains("Operating system:"));
        assert!(prompt.contains("Current directory:"));
        // Should contain tool guidance
        assert!(prompt.contains("<tools>"));
        assert!(prompt.contains("read_file"));
        assert!(prompt.contains("grep_search"));
        assert!(prompt.contains("Maximize parallel execution"));
        // Tool hints should only include available tools
        assert!(prompt.contains("grep_search"));
        assert!(prompt.contains("read_file"));
        // bash and list_directory are NOT in the tool set, so their hints should be absent
        assert!(!prompt.contains("→ bash"));
        assert!(!prompt.contains("→ list_directory"));
        // Should contain constraints
        assert!(prompt.contains("<constraints>"));
        assert!(prompt.contains("isolated subagent context"));

        // Verify ordering: environment before agent_identity
        let env_pos = prompt.find("<environment>").unwrap();
        let identity_pos = prompt.find("<agent_identity>").unwrap();
        assert!(env_pos < identity_pos, "environment should come before agent_identity for cache efficiency");
    }

    #[test]
    fn test_build_effective_prompt_with_shared_context() {
        let base = "You are a code reviewer.";
        let tools = vec![
            ToolInfo {
                name: "read_file".to_string(),
                description: "Read file contents".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
        ];
        let shared = "Architecture: modular Rust project with trait-based abstractions.\nKey types: LlmApi, ToolExecutor, ChatMessage";

        let prompt = build_effective_prompt_with_context(base, &tools, true, Some(shared));

        assert!(prompt.contains("<shared_context>"));
        assert!(prompt.contains("modular Rust project"));
        assert!(prompt.contains("LlmApi"));
        assert!(prompt.contains("cross-module interfaces"));
    }

    #[test]
    fn test_build_effective_prompt_with_empty_shared_context() {
        let base = "You are a code reviewer.";
        let prompt = build_effective_prompt_with_context(base, &[], false, Some("  "));
        assert!(!prompt.contains("<shared_context>"));
    }

    #[test]
    fn test_build_effective_prompt_without_tools() {
        let base = "You are a planning agent.";
        let prompt = build_effective_prompt(base, &[], false);

        // Cache-friendly ordering: environment first
        assert!(prompt.starts_with("<environment>"));
        // Should contain the base prompt in agent_identity
        assert!(prompt.contains("<agent_identity>"));
        assert!(prompt.contains("You are a planning agent."));
        // Should contain environment section
        assert!(prompt.contains("<environment>"));
        // Should NOT contain tool guidance
        assert!(!prompt.contains("<tools>"));
        // Should contain constraints (without tool-specific ones)
        assert!(prompt.contains("<constraints>"));
        assert!(prompt.contains("isolated subagent context"));
        assert!(!prompt.contains("tool names or protocols"));
    }

    #[test]
    fn test_environment_section_has_required_fields() {
        let section = build_environment_section();
        assert!(section.contains("Operating system:"));
        assert!(section.contains("Default shell:"));
        assert!(section.contains("Current directory:"));
        assert!(section.contains("Today's date:"));
    }

    #[test]
    fn test_tool_guidance_lists_all_tools() {
        let tools = vec![
            ToolInfo {
                name: "bash".to_string(),
                description: "Execute shell commands".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
            ToolInfo {
                name: "list_directory".to_string(),
                description: "List directory contents".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
        ];

        let section = build_tool_guidance_section(&tools);
        assert!(section.contains("bash"));
        assert!(section.contains("list_directory"));
        assert!(section.contains("Execute shell commands"));
        // Tool hints should only include tools that are actually available
        assert!(section.contains("Shell commands → bash"));
        assert!(section.contains("Directory listing → list_directory"));
        // Should NOT include tools that aren't in the list
        assert!(!section.contains("grep_search"));
        assert!(!section.contains("read_file"));
        assert!(!section.contains("search_files"));
    }

    #[test]
    fn test_tool_guidance_conditional_hints() {
        // Test with a minimal tool set — only read_file
        let tools = vec![
            ToolInfo {
                name: "read_file".to_string(),
                description: "Read file contents".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
        ];

        let section = build_tool_guidance_section(&tools);
        assert!(section.contains("read_file"));
        assert!(section.contains("Known file path → read_file"));
        // Should NOT mention tools not in the set
        assert!(!section.contains("→ bash"));
        assert!(!section.contains("→ grep_search"));
        assert!(!section.contains("→ list_directory"));
        assert!(!section.contains("→ search_files"));
        // take_note not available, so no take_note hint
        assert!(!section.contains("take_note"));
    }

    #[test]
    fn test_prompt_ordering_cache_friendly() {
        let base = "You are a specialized agent.";
        let tools = vec![
            ToolInfo {
                name: "read_file".to_string(),
                description: "Read file contents".to_string(),
                source: "built-in".to_string(),
                usage_hint: None,
            },
        ];
        let shared = "Project uses microservices architecture.";

        let prompt = build_effective_prompt_with_context(base, &tools, true, Some(shared));

        // Verify cache-friendly ordering:
        // environment < constraints < tools < shared_context < agent_identity
        let env_pos = prompt.find("<environment>").unwrap();
        let constraints_pos = prompt.find("<constraints>").unwrap();
        let tools_pos = prompt.find("<tools>").unwrap();
        let shared_pos = prompt.find("<shared_context>").unwrap();
        let identity_pos = prompt.find("<agent_identity>").unwrap();

        assert!(env_pos < constraints_pos, "environment should come before constraints");
        assert!(constraints_pos < tools_pos, "constraints should come before tools");
        assert!(tools_pos < shared_pos, "tools should come before shared_context");
        assert!(shared_pos < identity_pos, "shared_context should come before agent_identity");
    }

    #[test]
    fn test_constraints_with_tools() {
        let section = build_constraints_section(true);
        assert!(section.contains("tool names or protocols"));
        assert!(section.contains("Do not fabricate"));
    }

    #[test]
    fn test_constraints_without_tools() {
        let section = build_constraints_section(false);
        assert!(!section.contains("tool names or protocols"));
        assert!(!section.contains("Do not fabricate"));
    }
}
